// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
  aws_appsync_graphqlEndpoint: 'https://3czclhy4s5hzhjdeb3gdjnwtsi.appsync-api.ap-northeast-1.amazonaws.com/graphql',
  aws_project_region: 'ap-northeast-1',
  aws_appsync_region: 'ap-northeast-1',
  aws_appsync_authenticationType: 'apiKey',
  aws_appsync_apiKey: 'da2-m5ll7romdbdxnpnisplhxc2nnq'
};

export default config;